### PR TITLE
Fix tree

### PR DESCRIPTION
**Pull request by nyancrimew**
luv ya bæ @ZerNico :heart:

**DO NOT FUCKING MERGE THIS OR THE UNIVERSE (LOL PUN...) WILL BE DESTROYED**

### CODE REVIEW

**Comment by msfjarvis** [comment]
Your way of fixing things is rather admirable I'd say

**Comment by nyancrimew** [comment]
@MSF-Jarvis ikr
this just fixed all the bugs in one go
EDIT: Atleast it removed them

**Comment by amardeep434** [comment]
Lmfao

**Comment by Shreeesha** [comment]
Looks good to me. Approved

**Comment by nyancrimew** [comment]
Just waiting for @ZerNico to merge now

**Comment by PMS22** [comment]
😂😂😂

**Comment by ZerNico** [comment]
Thank you my bæ for your hard work! I really really appreciate that. It'll improve the quality of my builds so much. I love you 
Donut touch my wood anymore!

**Comment by akhilnarang** [comment]
+1 merge it

**Comment by RajGopi7** [comment]
Just merge it. Now

**Comment by ZerNico** [comment]
Give me a bit to analyze all the changes.

**Comment by artem** [comment]
@ZerNico how many "Z" letters were removed?

**Comment by nyancrimew** [comment]
@ab123321 should be something around 150000 if I remember it correctly

**Comment by ZerNico** [comment]
@deletescape sorry but you didn't add a new readme! I can't merge it like that

**Comment by nyancrimew** [comment]
@ZerNico will add a new readme tomorrow, I totally did that already but forgot to `git add README.md`

**Pull request closed without merging**
